kind: pipeline
type: kubernetes
name: pi3-kube

steps:
- name: publish
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: jtbarclay/drone-kubernetes
    tags: ["arm", "latest"]

node_selector:
  kubernetes.io/arch: arm
---
kind: pipeline
type: kubernetes
name: pi4-kube

platform:
  arch: arm64

steps:
- name: publish
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: jtbarclay/drone-kubernetes
    tags: ["arm64", "latest"]

node_selector:
  kubernetes.io/arch: arm64