kind: pipeline
type: kubernetes
name: pi-kube

platform:
  os: linux
  arch: arm

steps:
- name: publish
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: jtbarclay/drone-kubernetes
    tags: ["arm", "latest"]